config/routes.rb
Rails.application.routes.draw do
  get 'api/monsters'
  get 'api/hungry'
  get 'api/happy'

  get '/map' => 'page#map', :as => 'map'

  root 'static_pages#home'

  get '/help' => 'static_pages#help', :as => 'help'

  get '/about' => 'static_pages#about', :as => 'about'

  get '/ranking' => 'static_pages#ranking', :as => 'ranking'

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks", registrations: 'registrations'  }

  resources :monsters

  post 'monsters/:id/feed/:score' => 'monsters#feed', :as => 'feed_monster'

  resources :feeds
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer class="page-footer footer">
    <div class="footer-copyright">
        <div class="container">
        © 2017 Copyright Ludejo
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="header">
    <div class="nav-wrapper">
            
      <a href="#!" id="brand-logo" class="brand-logo"><img src="<%= asset_path('ludejo.svg')%>"></a>
      
      <a href="#" data-activates="mobile-menu" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Monsters", monsters_path %></li>
          <li><%= link_to "Ranking", ranking_path %></li>
          <li><%= link_to "Map", map_path %></li>
          <li><%= link_to "Info", help_path %></li>
          <li><%= link_to "About", about_path %></li>
          <% unless current_user %>
          <li id="nav-sign-up" class="nav-items"><%= link_to "Sign-up", new_user_registration_path %></li>
          <li id="nav-login" class="nav-items"><%= link_to "Login", new_user_session_path %></li>
          <% else %>
          <li class="nav-items"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% end %>
      </ul>
      <ul class="side-nav" id="mobile-menu">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Monsters", monsters_path %></li>
        <li><%= link_to "Ranking", ranking_path %></li>
        <li><%= link_to "Map", map_path %></li>
        <li><%= link_to "Info", help_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% unless current_user %>
        <li id="nav-sign-up" class="nav-items"><%= link_to "Sign-up", new_user_registration_path %></li>
        <li id="nav-login" class="nav-items"><%= link_to "Login", new_user_session_path %></li>
        <% else %>
        <li class="nav-items"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </nav>

  <!-- Dropdown Structure -->
<ul id="dropdownHelp" class="dropdown-content">
  <li class="nav-info"><%= link_to "Info", help_path %></li>
  <li><a href="#!">FAQ</a></li>
  <li class="divider"></li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'layouts/header' %>
    <div class="container content">
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>